# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 387fd2e0f61866adbf2d31bad046a82a5cae55dd04f532e94204e7d60c3c1a722fbc921451f1a3dcddf3372b7102a2f6656c9aa85df9eb1b9b44d7eee54ae801

test:
  secret_key_base: a7206a29a35f8ba581fe2a95ea0101405cca1acbbfd95a496687bc48fdf0b5db26b7c825d5a9232f45853bed0e4b95192596ab736fa1895d7cd9b3da2eb51056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
